"""empty message

Revision ID: 1aa7ef398283
Revises: b0d944a76c62
Create Date: 2021-09-12 15:44:51.487965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1aa7ef398283'
down_revision = 'b0d944a76c62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('age', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('grand_parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('age', sa.String(length=3), nullable=False),
    sa.Column('children_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['children_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('last_name'),
    sa.UniqueConstraint('last_name'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.drop_index('name', table_name='current_generation')
    op.drop_index('name_2', table_name='current_generation')
    op.drop_table('current_generation')
    op.drop_table('member')
    op.drop_index('name', table_name='grandparents')
    op.drop_index('name_2', table_name='grandparents')
    op.drop_table('grandparents')
    op.drop_index('email', table_name='user')
    op.drop_index('email_2', table_name='user')
    op.drop_table('user')
    op.add_column('parents', sa.Column('children_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'parents', ['last_name'])
    op.drop_constraint('parents_ibfk_1', 'parents', type_='foreignkey')
    op.create_foreign_key(None, 'parents', 'children', ['children_id'], ['id'])
    op.drop_column('parents', 'grandparent_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parents', sa.Column('grandparent_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'parents', type_='foreignkey')
    op.create_foreign_key('parents_ibfk_1', 'parents', 'grandparents', ['grandparent_id'], ['id'])
    op.drop_constraint(None, 'parents', type_='unique')
    op.drop_column('parents', 'children_id')
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.CheckConstraint('(`is_active` in (0,1))', name='user_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('email_2', 'user', ['email'], unique=False)
    op.create_index('email', 'user', ['email'], unique=False)
    op.create_table('grandparents',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name_2', 'grandparents', ['name'], unique=False)
    op.create_index('name', 'grandparents', ['name'], unique=False)
    op.create_table('member',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['member.id'], name='member_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('current_generation',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], name='current_generation_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name_2', 'current_generation', ['name'], unique=False)
    op.create_index('name', 'current_generation', ['name'], unique=False)
    op.drop_table('grand_parents')
    op.drop_table('children')
    # ### end Alembic commands ###
